version: '2.6'
services:

  tensorflowtts-2.6:
    container_name: tensorflowtts-2.6
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile-tf2.6

    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - .:/workspace
      - /mnt/data/:/mnt/data/

    runtime: nvidia
    tty: true
    command: /bin/bash
    environment:
      - CUDA_VISIBLE_DEVICES
