version: '2.6'
services:

  tensorflowtts-js2.6:

    container_name: tensorflowtts-js2.6
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile-tfjs2.6

    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./tensorflow_js/:/workspace
      - ./models:/workspace/models
      - /mnt/data:/mnt/data

    runtime: nvidia
    tty: true
    command: /bin/bash

    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Seoul
