version: '2.6'
services:
  tensorflowtts:
    build: .
    volumes:
      - .:/workspace
      - /mnt/data:/mnt/data
    runtime: nvidia
    tty: true
    command: /bin/bash
    environment:
      - CUDA_VISIBLE_DEVICES
