version: '2.6'
services:
  tensorflowtts:
    build: tf2.4/
    volumes:
      - .:/workspace
      - /mnt/data/input/:/mnt/data
    runtime: nvidia
    tty: true
    command: /bin/bash
    environment:
      - CUDA_VISIBLE_DEVICES
