FROM tensorflow/tensorflow:2.6.0-gpu

RUN sed -i 's:^:#:g' /etc/apt/sources.list.d/cuda.list


RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --allow-downgrades --allow-change-held-packages \
    cmake \ 
    curl \
    vim \ 
    bzip2 \
    unzip \
    wget 


RUN pip install \
    tensorflowjs==3.9.0


# Install NodeJS
RUN curl --silent --location https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install --yes nodejs

# Install yarn
RUN npm install -g yarn

# Install tfjs-node
RUN yarn add @tensorflow/tfjs
RUN yarn add @tensorflow/tfjs-node

# Clean up commands
RUN apt-get autoremove -y && apt-get clean && \
    rm -rf /usr/local/src/*

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN mkdir /workspace
WORKDIR /workspace

ENV HOME /workspace
