FROM tensorflow/tensorflow:2.6.0-gpu

RUN sed -i 's:^:#:g' /etc/apt/sources.list.d/cuda.list


RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --allow-downgrades --allow-change-held-packages \
    cmake \ 
    curl \
    vim \ 
    bzip2 \
    unzip \
    wget 


RUN pip install \
    tensorflowjs==2.6.0 

RUN mkdir /workspace
WORKDIR /workspace
