FROM tensorflow/tensorflow:2.3.1-gpu

RUN sed -i 's:^:#:g' /etc/apt/sources.list.d/cuda.list

RUN apt-get update && apt-get install -y \
    zsh tmux wget git libsndfile1 sox vim \
    && \
    pip install \
    ipython==7.16.1  \
    h5py==2.10.0 \
    git+https://github.com/TensorSpeech/TensorflowTTS.git@1.6.1 \
    git+https://github.com/repodiac/german_transliterate.git#egg=german_transliterate

RUN mkdir /workspace
WORKDIR /workspace
