FROM ubuntu:18.04


RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --allow-downgrades --allow-change-held-packages \
    cmake \ 
    tzdata \
    curl \
    vim \ 
    bzip2 \
    unzip \
    wget \
    python3-distutils \ 
    python3.6

RUN ln -s /usr/bin/python3.6 /usr/bin/python && \ 
    curl https://bootstrap.pypa.io/pip/3.6/get-pip.py | python 

RUN pip install \
    tensorflowjs==2.6.0

RUN mkdir /workspace
WORKDIR /workspace
